name: Deploy
concurrency: staging
on:
  push:
    branches:
    - main
  workflow_dispatch:
jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: staging
    steps:
    - uses: actions/checkout@v3
    - uses: nixbuild/nix-quick-install-action@v18
      with:
        nix_conf: experimental-features = nix-command flakes
    - uses: cachix/cachix-action@v11
      with:
        name: enarx
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
    - name: Setup SSH
      env:
        SSH_AUTH_SOCK: /tmp/ssh_agent.sock
      run: |
        umask 0077
        mkdir -p ~/.ssh
        printf '%s' '${{ secrets.SSH_KEY }}' > ~/.ssh/id_ed25519
        chmod 400 ~/.ssh/id_ed25519
        ssh-agent -a $SSH_AUTH_SOCK
        ssh-add ~/.ssh/id_ed25519
        ssh-keyscan attest.staging.profian.com >> ~/.ssh/known_hosts
        ssh-keyscan attest.testing.profian.com >> ~/.ssh/known_hosts
        ssh-keyscan benefice.testing.profian.com >> ~/.ssh/known_hosts
        ssh-keyscan store.staging.profian.com >> ~/.ssh/known_hosts
        ssh-keyscan store.testing.profian.com >> ~/.ssh/known_hosts
    - name: Deploy
      env:
        SSH_AUTH_SOCK: /tmp/ssh_agent.sock
      run: |
        nix develop '.#base' -c deploy -s --targets \
          '.#attest-staging' \
          '.#attest-testing' \
          '.#benefice-testing' \
          '.#store-staging' \
          '.#store-testing'
